name: 'create-lighthouse-ci-config-files'
description: 'Create .lighthouserc.json for `desktop, mobile` form factor'
author: 'kurly'
inputs:
  URL_PREFIX:
    required: false
    description: 'URL Prefix (ex: http://localhost:3000)'

  URL_LIST:
    required: true
    description: 'Test target url list'

outputs:
  MOBILE_CONFIG_FILE_NAME:
    description: 'Mobile form factor config file'
  DESKTOP_CONFIG_FILE_NAME:
    description: 'Desktop form factor config file'

runs:
  using: 'node16'
  main: 'dist/index.js'
